// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LoginAccountResponse = { "type": "apiKey", } | { "type": "chatgpt", loginId: string, 
/**
 * URL the client should open in a browser to initiate the OAuth flow.
 */
authUrl: string, } | { "type": "chatgptAuthTokens", };
