// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Determines the conditions under which the user is consulted to approve
 * running the command proposed by Codex.
 */
export type AskForApproval = "untrusted" | "on-failure" | "on-request" | "never";
