// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthMode } from "./AuthMode";

/**
 * Deprecated notification. Use AccountUpdatedNotification instead.
 */
export type AuthStatusChangeNotification = { authMethod: AuthMode | null, };
