// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ByteRange = { 
/**
 * Start byte offset (inclusive) within the UTF-8 text buffer.
 */
start: number, 
/**
 * End byte offset (exclusive) within the UTF-8 text buffer.
 */
end: number, };
