// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadId } from "./ThreadId";

export type CollabWaitingBeginEvent = { 
/**
 * Thread ID of the sender.
 */
sender_thread_id: ThreadId, 
/**
 * Thread ID of the receivers.
 */
receiver_thread_ids: Array<ThreadId>, 
/**
 * ID of the waiting call.
 */
call_id: string, };
