// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentStatus } from "./AgentStatus";
import type { ThreadId } from "./ThreadId";

export type CollabCloseEndEvent = { 
/**
 * Identifier for the collab tool call.
 */
call_id: string, 
/**
 * Thread ID of the sender.
 */
sender_thread_id: ThreadId, 
/**
 * Thread ID of the receiver.
 */
receiver_thread_id: ThreadId, 
/**
 * Last known status of the receiver agent reported to the sender agent before
 * the close.
 */
status: AgentStatus, };
