// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentStatus } from "./AgentStatus";
import type { ThreadId } from "./ThreadId";

export type CollabWaitingEndEvent = { 
/**
 * Thread ID of the sender.
 */
sender_thread_id: ThreadId, 
/**
 * ID of the waiting call.
 */
call_id: string, 
/**
 * Last known status of the receiver agents reported to the sender agent.
 */
statuses: { [key in ThreadId]?: AgentStatus }, };
