// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CustomPrompt = { name: string, path: string, content: string, description: string | null, argument_hint: string | null, };
