// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecCommandSource } from "./ExecCommandSource";
import type { ExecCommandStatus } from "./ExecCommandStatus";
import type { ParsedCommand } from "./ParsedCommand";

export type ExecCommandEndEvent = { 
/**
 * Identifier for the ExecCommandBegin that finished.
 */
call_id: string, 
/**
 * Identifier for the underlying PTY process (when available).
 */
process_id?: string, 
/**
 * Turn ID that this command belongs to.
 */
turn_id: string, 
/**
 * The command that was executed.
 */
command: Array<string>, 
/**
 * The command's working directory if not the default cwd for the agent.
 */
cwd: string, parsed_cmd: Array<ParsedCommand>, 
/**
 * Where the command originated. Defaults to Agent for backward compatibility.
 */
source: ExecCommandSource, 
/**
 * Raw input sent to a unified exec session (if this is an interaction event).
 */
interaction_input?: string, 
/**
 * Captured stdout
 */
stdout: string, 
/**
 * Captured stderr
 */
stderr: string, 
/**
 * Captured aggregated output
 */
aggregated_output: string, 
/**
 * The command's exit code.
 */
exit_code: number, 
/**
 * The duration of the command execution.
 */
duration: string, 
/**
 * Formatted output from the command, as seen by the model.
 */
formatted_output: string, 
/**
 * Completion status for this command execution.
 */
status: ExecCommandStatus, };
