// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadId } from "./ThreadId";
import type { TurnItem } from "./TurnItem";

export type ItemCompletedEvent = { thread_id: ThreadId, turn_id: string, item: TurnItem, };
