// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkillsListEntry } from "./SkillsListEntry";

/**
 * Response payload for `Op::ListSkills`.
 */
export type ListSkillsResponseEvent = { skills: Array<SkillsListEntry>, };
