// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Deprecated in favor of AccountLoginCompletedNotification.
 */
export type LoginChatGptCompleteNotification = { loginId: string, success: boolean, error: string | null, };
