// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type McpAuthStatus = "unsupported" | "not_logged_in" | "bearer_token" | "o_auth";
