// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpStartupStatus } from "./McpStartupStatus";

export type McpStartupUpdateEvent = { 
/**
 * Server name being started.
 */
server: string, 
/**
 * Current startup status.
 */
status: McpStartupStatus, };
