// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpStartupFailure } from "./McpStartupFailure";

export type McpStartupCompleteEvent = { ready: Array<string>, failed: Array<McpStartupFailure>, cancelled: Array<string>, };
