// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "./AbsolutePathBuf";

/**
 * Determines how read-only file access is granted inside a restricted
 * sandbox.
 */
export type ReadOnlyAccess = { "type": "restricted", 
/**
 * Include built-in platform read roots required for basic process
 * execution.
 */
include_platform_defaults: boolean, 
/**
 * Additional absolute roots that should be readable.
 */
readable_roots?: Array<AbsolutePathBuf>, } | { "type": "full-access" };
