// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response payload for `Op::DownloadRemoteSkill`.
 */
export type RemoteSkillDownloadedEvent = { id: string, name: string, path: string, };
