// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewLineRange } from "./ReviewLineRange";

/**
 * Location of the code related to a review finding.
 */
export type ReviewCodeLocation = { absolute_file_path: string, line_range: ReviewLineRange, };
