// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Inclusive line range in a file associated with the finding.
 */
export type ReviewLineRange = { start: number, end: number, };
