// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewFinding } from "./ReviewFinding";

/**
 * Structured review result produced by a child review session.
 */
export type ReviewOutputEvent = { findings: Array<ReviewFinding>, overall_correctness: string, overall_explanation: string, overall_confidence_score: number, };
