// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "./AbsolutePathBuf";
import type { NetworkAccess } from "./NetworkAccess";
import type { ReadOnlyAccess } from "./ReadOnlyAccess";

/**
 * Determines execution restrictions for model shell commands.
 */
export type SandboxPolicy = { "type": "danger-full-access" } | { "type": "read-only", 
/**
 * Read access granted while running under this policy.
 */
access?: ReadOnlyAccess, } | { "type": "external-sandbox", 
/**
 * Whether the external sandbox permits outbound network traffic.
 */
network_access: NetworkAccess, } | { "type": "workspace-write", 
/**
 * Additional folders (beyond cwd and possibly TMPDIR) that should be
 * writable from within the sandbox.
 */
writable_roots?: Array<AbsolutePathBuf>, 
/**
 * Read access granted while running under this policy.
 */
read_only_access?: ReadOnlyAccess, 
/**
 * When set to `true`, outbound network access is allowed. `false` by
 * default.
 */
network_access: boolean, 
/**
 * When set to `true`, will NOT include the per-user `TMPDIR`
 * environment variable among the default writable roots. Defaults to
 * `false`.
 */
exclude_tmpdir_env_var: boolean, 
/**
 * When set to `true`, will NOT include the `/tmp` among the default
 * writable roots on UNIX. Defaults to `false`.
 */
exclude_slash_tmp: boolean, };
