// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TerminalInteractionEvent = { 
/**
 * Identifier for the ExecCommandBegin that produced this chunk.
 */
call_id: string, 
/**
 * Process id associated with the running command.
 */
process_id: string, 
/**
 * Stdin sent to the running session.
 */
stdin: string, };
