// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlanItemArg } from "./PlanItemArg";

export type UpdatePlanArgs = { 
/**
 * Arguments for the `update_plan` todo/checklist tool (not plan mode).
 */
explanation: string | null, plan: Array<PlanItemArg>, };
