// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TextElement } from "./TextElement";

/**
 * User input
 */
export type UserInput = { "type": "text", text: string, 
/**
 * UI-defined spans within `text` that should be treated as special elements.
 * These are byte ranges into the UTF-8 `text` buffer and are used to render
 * or persist rich input markers (e.g., image placeholders) across history
 * and resume without mutating the literal text.
 */
text_elements: Array<TextElement>, } | { "type": "image", image_url: string, } | { "type": "local_image", path: string, } | { "type": "skill", name: string, path: string, } | { "type": "mention", name: string, path: string, };
