name: Sync Upstream

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT || github.token }}

      - name: Sync upstream branch
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          git remote add upstream https://github.com/openclaw/openclaw.git
          git fetch upstream

          git checkout -B upstream upstream/main
          git push origin upstream --force
